### ISSUE TITLE
a:hover property leaks into buttons

### ISSUE THREAD

**Issue by mrinsin** [mrinsin/sarahs_blog#34]
Edit and destroy buttons on concert and book show pages on hover look weird

**Comment by cpena002** [comment]
Fixed issues by adding: 
.btn-info:hover {
    background: #5bc0de !important;
  }

  .btn-info:visited {
    background: inherit !important;
  }

  .btn-danger:hover {
    background: red !important;
  }

  .btn-danger:visited {
    background: inherit !important;
  }
